// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.school.domain;

import com.mycompany.school.domain.AttendenceSheet;
import com.mycompany.school.domain.AttendenceSheetDataOnDemand;
import com.mycompany.school.domain.Staff;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Iterator;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect AttendenceSheetDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AttendenceSheetDataOnDemand: @Component;
    
    private Random AttendenceSheetDataOnDemand.rnd = new SecureRandom();
    
    private java.util.List<AttendenceSheet> AttendenceSheetDataOnDemand.data;
    
    public AttendenceSheet AttendenceSheetDataOnDemand.getNewTransientAttendenceSheet(int index) {
        AttendenceSheet obj = new AttendenceSheet();
        setAttendenceDate(obj, index);
        setAttendenceList(obj, index);
        setStaff(obj, index);
        return obj;
    }
    
    public void AttendenceSheetDataOnDemand.setAttendenceDate(AttendenceSheet obj, int index) {
        Date attendenceDate = null;
        obj.setAttendenceDate(attendenceDate);
    }
    
    public void AttendenceSheetDataOnDemand.setAttendenceList(AttendenceSheet obj, int index) {
        List attendenceList = null;
        obj.setAttendenceList(attendenceList);
    }
    
    public void AttendenceSheetDataOnDemand.setStaff(AttendenceSheet obj, int index) {
        Staff staff = null;
        obj.setStaff(staff);
    }
    
    public AttendenceSheet AttendenceSheetDataOnDemand.getSpecificAttendenceSheet(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        AttendenceSheet obj = data.get(index);
        Long id = obj.getId();
        return AttendenceSheet.findAttendenceSheet(id);
    }
    
    public AttendenceSheet AttendenceSheetDataOnDemand.getRandomAttendenceSheet() {
        init();
        AttendenceSheet obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return AttendenceSheet.findAttendenceSheet(id);
    }
    
    public boolean AttendenceSheetDataOnDemand.modifyAttendenceSheet(AttendenceSheet obj) {
        return false;
    }
    
    public void AttendenceSheetDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = AttendenceSheet.findAttendenceSheetEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'AttendenceSheet' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<AttendenceSheet>();
        for (int i = 0; i < 10; i++) {
            AttendenceSheet obj = getNewTransientAttendenceSheet(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
