// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.school.domain;

import com.mycompany.school.domain.ClassSection;
import com.mycompany.school.domain.ClassSectionDataOnDemand;
import com.mycompany.school.domain.ClassSectionIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ClassSectionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ClassSectionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ClassSectionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ClassSectionIntegrationTest: @Transactional;
    
    @Autowired
    ClassSectionDataOnDemand ClassSectionIntegrationTest.dod;
    
    @Test
    public void ClassSectionIntegrationTest.testCountClassSections() {
        Assert.assertNotNull("Data on demand for 'ClassSection' failed to initialize correctly", dod.getRandomClassSection());
        long count = ClassSection.countClassSections();
        Assert.assertTrue("Counter for 'ClassSection' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ClassSectionIntegrationTest.testFindClassSection() {
        ClassSection obj = dod.getRandomClassSection();
        Assert.assertNotNull("Data on demand for 'ClassSection' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClassSection' failed to provide an identifier", id);
        obj = ClassSection.findClassSection(id);
        Assert.assertNotNull("Find method for 'ClassSection' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ClassSection' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ClassSectionIntegrationTest.testFindAllClassSections() {
        Assert.assertNotNull("Data on demand for 'ClassSection' failed to initialize correctly", dod.getRandomClassSection());
        long count = ClassSection.countClassSections();
        Assert.assertTrue("Too expensive to perform a find all test for 'ClassSection', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ClassSection> result = ClassSection.findAllClassSections();
        Assert.assertNotNull("Find all method for 'ClassSection' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ClassSection' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ClassSectionIntegrationTest.testFindClassSectionEntries() {
        Assert.assertNotNull("Data on demand for 'ClassSection' failed to initialize correctly", dod.getRandomClassSection());
        long count = ClassSection.countClassSections();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ClassSection> result = ClassSection.findClassSectionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ClassSection' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ClassSection' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ClassSectionIntegrationTest.testFlush() {
        ClassSection obj = dod.getRandomClassSection();
        Assert.assertNotNull("Data on demand for 'ClassSection' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClassSection' failed to provide an identifier", id);
        obj = ClassSection.findClassSection(id);
        Assert.assertNotNull("Find method for 'ClassSection' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyClassSection(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ClassSection' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClassSectionIntegrationTest.testMergeUpdate() {
        ClassSection obj = dod.getRandomClassSection();
        Assert.assertNotNull("Data on demand for 'ClassSection' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClassSection' failed to provide an identifier", id);
        obj = ClassSection.findClassSection(id);
        boolean modified =  dod.modifyClassSection(obj);
        Integer currentVersion = obj.getVersion();
        ClassSection merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ClassSection' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClassSectionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ClassSection' failed to initialize correctly", dod.getRandomClassSection());
        ClassSection obj = dod.getNewTransientClassSection(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ClassSection' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ClassSection' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ClassSection' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ClassSectionIntegrationTest.testRemove() {
        ClassSection obj = dod.getRandomClassSection();
        Assert.assertNotNull("Data on demand for 'ClassSection' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClassSection' failed to provide an identifier", id);
        obj = ClassSection.findClassSection(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ClassSection' with identifier '" + id + "'", ClassSection.findClassSection(id));
    }
    
}
