// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.school.domain;

import com.mycompany.school.domain.ClassSection;
import com.mycompany.school.domain.ClassSectionDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ClassSectionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ClassSectionDataOnDemand: @Component;
    
    private Random ClassSectionDataOnDemand.rnd = new SecureRandom();
    
    private List<ClassSection> ClassSectionDataOnDemand.data;
    
    public ClassSection ClassSectionDataOnDemand.getNewTransientClassSection(int index) {
        ClassSection obj = new ClassSection();
        setName(obj, index);
        return obj;
    }
    
    public void ClassSectionDataOnDemand.setName(ClassSection obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public ClassSection ClassSectionDataOnDemand.getSpecificClassSection(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ClassSection obj = data.get(index);
        Long id = obj.getId();
        return ClassSection.findClassSection(id);
    }
    
    public ClassSection ClassSectionDataOnDemand.getRandomClassSection() {
        init();
        ClassSection obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ClassSection.findClassSection(id);
    }
    
    public boolean ClassSectionDataOnDemand.modifyClassSection(ClassSection obj) {
        return false;
    }
    
    public void ClassSectionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ClassSection.findClassSectionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ClassSection' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ClassSection>();
        for (int i = 0; i < 10; i++) {
            ClassSection obj = getNewTransientClassSection(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
