// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.school.domain;

import com.mycompany.school.domain.Designation;
import com.mycompany.school.domain.DesignationDataOnDemand;
import com.mycompany.school.domain.DesignationIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DesignationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DesignationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DesignationIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DesignationIntegrationTest: @Transactional;
    
    @Autowired
    DesignationDataOnDemand DesignationIntegrationTest.dod;
    
    @Test
    public void DesignationIntegrationTest.testCountDesignations() {
        Assert.assertNotNull("Data on demand for 'Designation' failed to initialize correctly", dod.getRandomDesignation());
        long count = Designation.countDesignations();
        Assert.assertTrue("Counter for 'Designation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DesignationIntegrationTest.testFindDesignation() {
        Designation obj = dod.getRandomDesignation();
        Assert.assertNotNull("Data on demand for 'Designation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Designation' failed to provide an identifier", id);
        obj = Designation.findDesignation(id);
        Assert.assertNotNull("Find method for 'Designation' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Designation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DesignationIntegrationTest.testFindAllDesignations() {
        Assert.assertNotNull("Data on demand for 'Designation' failed to initialize correctly", dod.getRandomDesignation());
        long count = Designation.countDesignations();
        Assert.assertTrue("Too expensive to perform a find all test for 'Designation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Designation> result = Designation.findAllDesignations();
        Assert.assertNotNull("Find all method for 'Designation' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Designation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DesignationIntegrationTest.testFindDesignationEntries() {
        Assert.assertNotNull("Data on demand for 'Designation' failed to initialize correctly", dod.getRandomDesignation());
        long count = Designation.countDesignations();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Designation> result = Designation.findDesignationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Designation' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Designation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DesignationIntegrationTest.testFlush() {
        Designation obj = dod.getRandomDesignation();
        Assert.assertNotNull("Data on demand for 'Designation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Designation' failed to provide an identifier", id);
        obj = Designation.findDesignation(id);
        Assert.assertNotNull("Find method for 'Designation' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDesignation(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Designation' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DesignationIntegrationTest.testMergeUpdate() {
        Designation obj = dod.getRandomDesignation();
        Assert.assertNotNull("Data on demand for 'Designation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Designation' failed to provide an identifier", id);
        obj = Designation.findDesignation(id);
        boolean modified =  dod.modifyDesignation(obj);
        Integer currentVersion = obj.getVersion();
        Designation merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Designation' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DesignationIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Designation' failed to initialize correctly", dod.getRandomDesignation());
        Designation obj = dod.getNewTransientDesignation(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Designation' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Designation' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Designation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DesignationIntegrationTest.testRemove() {
        Designation obj = dod.getRandomDesignation();
        Assert.assertNotNull("Data on demand for 'Designation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Designation' failed to provide an identifier", id);
        obj = Designation.findDesignation(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Designation' with identifier '" + id + "'", Designation.findDesignation(id));
    }
    
}
