// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.school.domain;

import com.mycompany.school.domain.Designation;
import com.mycompany.school.domain.DesignationDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect DesignationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DesignationDataOnDemand: @Component;
    
    private Random DesignationDataOnDemand.rnd = new SecureRandom();
    
    private List<Designation> DesignationDataOnDemand.data;
    
    public Designation DesignationDataOnDemand.getNewTransientDesignation(int index) {
        Designation obj = new Designation();
        setName(obj, index);
        return obj;
    }
    
    public void DesignationDataOnDemand.setName(Designation obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Designation DesignationDataOnDemand.getSpecificDesignation(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Designation obj = data.get(index);
        Long id = obj.getId();
        return Designation.findDesignation(id);
    }
    
    public Designation DesignationDataOnDemand.getRandomDesignation() {
        init();
        Designation obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Designation.findDesignation(id);
    }
    
    public boolean DesignationDataOnDemand.modifyDesignation(Designation obj) {
        return false;
    }
    
    public void DesignationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Designation.findDesignationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Designation' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Designation>();
        for (int i = 0; i < 10; i++) {
            Designation obj = getNewTransientDesignation(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
