// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.school.domain;

import com.mycompany.school.domain.EventCategory;
import com.mycompany.school.domain.EventCategoryDataOnDemand;
import com.mycompany.school.domain.EventCategoryIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EventCategoryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EventCategoryIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EventCategoryIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EventCategoryIntegrationTest: @Transactional;
    
    @Autowired
    EventCategoryDataOnDemand EventCategoryIntegrationTest.dod;
    
    @Test
    public void EventCategoryIntegrationTest.testCountEventCategorys() {
        Assert.assertNotNull("Data on demand for 'EventCategory' failed to initialize correctly", dod.getRandomEventCategory());
        long count = EventCategory.countEventCategorys();
        Assert.assertTrue("Counter for 'EventCategory' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EventCategoryIntegrationTest.testFindEventCategory() {
        EventCategory obj = dod.getRandomEventCategory();
        Assert.assertNotNull("Data on demand for 'EventCategory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EventCategory' failed to provide an identifier", id);
        obj = EventCategory.findEventCategory(id);
        Assert.assertNotNull("Find method for 'EventCategory' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'EventCategory' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EventCategoryIntegrationTest.testFindAllEventCategorys() {
        Assert.assertNotNull("Data on demand for 'EventCategory' failed to initialize correctly", dod.getRandomEventCategory());
        long count = EventCategory.countEventCategorys();
        Assert.assertTrue("Too expensive to perform a find all test for 'EventCategory', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<EventCategory> result = EventCategory.findAllEventCategorys();
        Assert.assertNotNull("Find all method for 'EventCategory' illegally returned null", result);
        Assert.assertTrue("Find all method for 'EventCategory' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EventCategoryIntegrationTest.testFindEventCategoryEntries() {
        Assert.assertNotNull("Data on demand for 'EventCategory' failed to initialize correctly", dod.getRandomEventCategory());
        long count = EventCategory.countEventCategorys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<EventCategory> result = EventCategory.findEventCategoryEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'EventCategory' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'EventCategory' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EventCategoryIntegrationTest.testFlush() {
        EventCategory obj = dod.getRandomEventCategory();
        Assert.assertNotNull("Data on demand for 'EventCategory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EventCategory' failed to provide an identifier", id);
        obj = EventCategory.findEventCategory(id);
        Assert.assertNotNull("Find method for 'EventCategory' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEventCategory(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'EventCategory' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EventCategoryIntegrationTest.testMergeUpdate() {
        EventCategory obj = dod.getRandomEventCategory();
        Assert.assertNotNull("Data on demand for 'EventCategory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EventCategory' failed to provide an identifier", id);
        obj = EventCategory.findEventCategory(id);
        boolean modified =  dod.modifyEventCategory(obj);
        Integer currentVersion = obj.getVersion();
        EventCategory merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'EventCategory' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EventCategoryIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'EventCategory' failed to initialize correctly", dod.getRandomEventCategory());
        EventCategory obj = dod.getNewTransientEventCategory(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'EventCategory' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'EventCategory' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'EventCategory' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EventCategoryIntegrationTest.testRemove() {
        EventCategory obj = dod.getRandomEventCategory();
        Assert.assertNotNull("Data on demand for 'EventCategory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EventCategory' failed to provide an identifier", id);
        obj = EventCategory.findEventCategory(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'EventCategory' with identifier '" + id + "'", EventCategory.findEventCategory(id));
    }
    
}
