// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.school.domain;

import com.mycompany.school.domain.EventCategory;
import com.mycompany.school.domain.EventCategoryDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect EventCategoryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EventCategoryDataOnDemand: @Component;
    
    private Random EventCategoryDataOnDemand.rnd = new SecureRandom();
    
    private List<EventCategory> EventCategoryDataOnDemand.data;
    
    public EventCategory EventCategoryDataOnDemand.getNewTransientEventCategory(int index) {
        EventCategory obj = new EventCategory();
        setName(obj, index);
        return obj;
    }
    
    public void EventCategoryDataOnDemand.setName(EventCategory obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public EventCategory EventCategoryDataOnDemand.getSpecificEventCategory(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        EventCategory obj = data.get(index);
        Long id = obj.getId();
        return EventCategory.findEventCategory(id);
    }
    
    public EventCategory EventCategoryDataOnDemand.getRandomEventCategory() {
        init();
        EventCategory obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return EventCategory.findEventCategory(id);
    }
    
    public boolean EventCategoryDataOnDemand.modifyEventCategory(EventCategory obj) {
        return false;
    }
    
    public void EventCategoryDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = EventCategory.findEventCategoryEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'EventCategory' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<EventCategory>();
        for (int i = 0; i < 10; i++) {
            EventCategory obj = getNewTransientEventCategory(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
