// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.school.domain;

import com.mycompany.school.domain.EventType;
import com.mycompany.school.domain.EventTypeDataOnDemand;
import com.mycompany.school.domain.EventTypeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EventTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EventTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EventTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EventTypeIntegrationTest: @Transactional;
    
    @Autowired
    EventTypeDataOnDemand EventTypeIntegrationTest.dod;
    
    @Test
    public void EventTypeIntegrationTest.testCountEventTypes() {
        Assert.assertNotNull("Data on demand for 'EventType' failed to initialize correctly", dod.getRandomEventType());
        long count = EventType.countEventTypes();
        Assert.assertTrue("Counter for 'EventType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EventTypeIntegrationTest.testFindEventType() {
        EventType obj = dod.getRandomEventType();
        Assert.assertNotNull("Data on demand for 'EventType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EventType' failed to provide an identifier", id);
        obj = EventType.findEventType(id);
        Assert.assertNotNull("Find method for 'EventType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'EventType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EventTypeIntegrationTest.testFindAllEventTypes() {
        Assert.assertNotNull("Data on demand for 'EventType' failed to initialize correctly", dod.getRandomEventType());
        long count = EventType.countEventTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'EventType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<EventType> result = EventType.findAllEventTypes();
        Assert.assertNotNull("Find all method for 'EventType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'EventType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EventTypeIntegrationTest.testFindEventTypeEntries() {
        Assert.assertNotNull("Data on demand for 'EventType' failed to initialize correctly", dod.getRandomEventType());
        long count = EventType.countEventTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<EventType> result = EventType.findEventTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'EventType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'EventType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EventTypeIntegrationTest.testFlush() {
        EventType obj = dod.getRandomEventType();
        Assert.assertNotNull("Data on demand for 'EventType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EventType' failed to provide an identifier", id);
        obj = EventType.findEventType(id);
        Assert.assertNotNull("Find method for 'EventType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEventType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'EventType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EventTypeIntegrationTest.testMergeUpdate() {
        EventType obj = dod.getRandomEventType();
        Assert.assertNotNull("Data on demand for 'EventType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EventType' failed to provide an identifier", id);
        obj = EventType.findEventType(id);
        boolean modified =  dod.modifyEventType(obj);
        Integer currentVersion = obj.getVersion();
        EventType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'EventType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EventTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'EventType' failed to initialize correctly", dod.getRandomEventType());
        EventType obj = dod.getNewTransientEventType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'EventType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'EventType' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'EventType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EventTypeIntegrationTest.testRemove() {
        EventType obj = dod.getRandomEventType();
        Assert.assertNotNull("Data on demand for 'EventType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EventType' failed to provide an identifier", id);
        obj = EventType.findEventType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'EventType' with identifier '" + id + "'", EventType.findEventType(id));
    }
    
}
