// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.school.domain;

import com.mycompany.school.domain.LeaveType;
import com.mycompany.school.domain.LeaveTypeDataOnDemand;
import com.mycompany.school.domain.LeaveTypeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LeaveTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LeaveTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LeaveTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: LeaveTypeIntegrationTest: @Transactional;
    
    @Autowired
    LeaveTypeDataOnDemand LeaveTypeIntegrationTest.dod;
    
    @Test
    public void LeaveTypeIntegrationTest.testCountLeaveTypes() {
        Assert.assertNotNull("Data on demand for 'LeaveType' failed to initialize correctly", dod.getRandomLeaveType());
        long count = LeaveType.countLeaveTypes();
        Assert.assertTrue("Counter for 'LeaveType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LeaveTypeIntegrationTest.testFindLeaveType() {
        LeaveType obj = dod.getRandomLeaveType();
        Assert.assertNotNull("Data on demand for 'LeaveType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LeaveType' failed to provide an identifier", id);
        obj = LeaveType.findLeaveType(id);
        Assert.assertNotNull("Find method for 'LeaveType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'LeaveType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LeaveTypeIntegrationTest.testFindAllLeaveTypes() {
        Assert.assertNotNull("Data on demand for 'LeaveType' failed to initialize correctly", dod.getRandomLeaveType());
        long count = LeaveType.countLeaveTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'LeaveType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<LeaveType> result = LeaveType.findAllLeaveTypes();
        Assert.assertNotNull("Find all method for 'LeaveType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'LeaveType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LeaveTypeIntegrationTest.testFindLeaveTypeEntries() {
        Assert.assertNotNull("Data on demand for 'LeaveType' failed to initialize correctly", dod.getRandomLeaveType());
        long count = LeaveType.countLeaveTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<LeaveType> result = LeaveType.findLeaveTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'LeaveType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'LeaveType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LeaveTypeIntegrationTest.testFlush() {
        LeaveType obj = dod.getRandomLeaveType();
        Assert.assertNotNull("Data on demand for 'LeaveType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LeaveType' failed to provide an identifier", id);
        obj = LeaveType.findLeaveType(id);
        Assert.assertNotNull("Find method for 'LeaveType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLeaveType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'LeaveType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LeaveTypeIntegrationTest.testMergeUpdate() {
        LeaveType obj = dod.getRandomLeaveType();
        Assert.assertNotNull("Data on demand for 'LeaveType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LeaveType' failed to provide an identifier", id);
        obj = LeaveType.findLeaveType(id);
        boolean modified =  dod.modifyLeaveType(obj);
        Integer currentVersion = obj.getVersion();
        LeaveType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'LeaveType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LeaveTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'LeaveType' failed to initialize correctly", dod.getRandomLeaveType());
        LeaveType obj = dod.getNewTransientLeaveType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'LeaveType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'LeaveType' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'LeaveType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LeaveTypeIntegrationTest.testRemove() {
        LeaveType obj = dod.getRandomLeaveType();
        Assert.assertNotNull("Data on demand for 'LeaveType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LeaveType' failed to provide an identifier", id);
        obj = LeaveType.findLeaveType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'LeaveType' with identifier '" + id + "'", LeaveType.findLeaveType(id));
    }
    
}
