// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.school.domain;

import com.mycompany.school.domain.StudentClassIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect StudentClassIntegrationTest_Roo_Configurable {
    
    declare @type: StudentClassIntegrationTest: @Configurable;
    
}
