// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.school.domain;

import com.mycompany.school.domain.StudentLeave;
import com.mycompany.school.domain.StudentLeaveDataOnDemand;
import com.mycompany.school.domain.StudentLeaveIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StudentLeaveIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StudentLeaveIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StudentLeaveIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StudentLeaveIntegrationTest: @Transactional;
    
    @Autowired
    StudentLeaveDataOnDemand StudentLeaveIntegrationTest.dod;
    
    @Test
    public void StudentLeaveIntegrationTest.testCountStudentLeaves() {
        Assert.assertNotNull("Data on demand for 'StudentLeave' failed to initialize correctly", dod.getRandomStudentLeave());
        long count = StudentLeave.countStudentLeaves();
        Assert.assertTrue("Counter for 'StudentLeave' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StudentLeaveIntegrationTest.testFindStudentLeave() {
        StudentLeave obj = dod.getRandomStudentLeave();
        Assert.assertNotNull("Data on demand for 'StudentLeave' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StudentLeave' failed to provide an identifier", id);
        obj = StudentLeave.findStudentLeave(id);
        Assert.assertNotNull("Find method for 'StudentLeave' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'StudentLeave' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StudentLeaveIntegrationTest.testFindAllStudentLeaves() {
        Assert.assertNotNull("Data on demand for 'StudentLeave' failed to initialize correctly", dod.getRandomStudentLeave());
        long count = StudentLeave.countStudentLeaves();
        Assert.assertTrue("Too expensive to perform a find all test for 'StudentLeave', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<StudentLeave> result = StudentLeave.findAllStudentLeaves();
        Assert.assertNotNull("Find all method for 'StudentLeave' illegally returned null", result);
        Assert.assertTrue("Find all method for 'StudentLeave' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StudentLeaveIntegrationTest.testFindStudentLeaveEntries() {
        Assert.assertNotNull("Data on demand for 'StudentLeave' failed to initialize correctly", dod.getRandomStudentLeave());
        long count = StudentLeave.countStudentLeaves();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<StudentLeave> result = StudentLeave.findStudentLeaveEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'StudentLeave' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'StudentLeave' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StudentLeaveIntegrationTest.testFlush() {
        StudentLeave obj = dod.getRandomStudentLeave();
        Assert.assertNotNull("Data on demand for 'StudentLeave' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StudentLeave' failed to provide an identifier", id);
        obj = StudentLeave.findStudentLeave(id);
        Assert.assertNotNull("Find method for 'StudentLeave' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStudentLeave(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'StudentLeave' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StudentLeaveIntegrationTest.testMergeUpdate() {
        StudentLeave obj = dod.getRandomStudentLeave();
        Assert.assertNotNull("Data on demand for 'StudentLeave' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StudentLeave' failed to provide an identifier", id);
        obj = StudentLeave.findStudentLeave(id);
        boolean modified =  dod.modifyStudentLeave(obj);
        Integer currentVersion = obj.getVersion();
        StudentLeave merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'StudentLeave' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StudentLeaveIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'StudentLeave' failed to initialize correctly", dod.getRandomStudentLeave());
        StudentLeave obj = dod.getNewTransientStudentLeave(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'StudentLeave' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'StudentLeave' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'StudentLeave' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StudentLeaveIntegrationTest.testRemove() {
        StudentLeave obj = dod.getRandomStudentLeave();
        Assert.assertNotNull("Data on demand for 'StudentLeave' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StudentLeave' failed to provide an identifier", id);
        obj = StudentLeave.findStudentLeave(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'StudentLeave' with identifier '" + id + "'", StudentLeave.findStudentLeave(id));
    }
    
}
