// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.school.domain;

import com.mycompany.school.domain.LeaveTypeDataOnDemand;
import com.mycompany.school.domain.StudentDataOnDemand;
import com.mycompany.school.domain.StudentLeave;
import com.mycompany.school.domain.StudentLeaveDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect StudentLeaveDataOnDemand_Roo_DataOnDemand {
    
    declare @type: StudentLeaveDataOnDemand: @Component;
    
    private Random StudentLeaveDataOnDemand.rnd = new SecureRandom();
    
    private List<StudentLeave> StudentLeaveDataOnDemand.data;
    
    @Autowired
    LeaveTypeDataOnDemand StudentLeaveDataOnDemand.leaveTypeDataOnDemand;
    
    @Autowired
    StudentDataOnDemand StudentLeaveDataOnDemand.studentDataOnDemand;
    
    public StudentLeave StudentLeaveDataOnDemand.getNewTransientStudentLeave(int index) {
        StudentLeave obj = new StudentLeave();
        setDescription(obj, index);
        setLeaveFrom(obj, index);
        setLeaveTo(obj, index);
        return obj;
    }
    
    public void StudentLeaveDataOnDemand.setDescription(StudentLeave obj, int index) {
        String description = "description_" + index;
        if (description.length() > 500) {
            description = description.substring(0, 500);
        }
        obj.setDescription(description);
    }
    
    public void StudentLeaveDataOnDemand.setLeaveFrom(StudentLeave obj, int index) {
        Date leaveFrom = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setLeaveFrom(leaveFrom);
    }
    
    public void StudentLeaveDataOnDemand.setLeaveTo(StudentLeave obj, int index) {
        Date leaveTo = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setLeaveTo(leaveTo);
    }
    
    public StudentLeave StudentLeaveDataOnDemand.getSpecificStudentLeave(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        StudentLeave obj = data.get(index);
        Long id = obj.getId();
        return StudentLeave.findStudentLeave(id);
    }
    
    public StudentLeave StudentLeaveDataOnDemand.getRandomStudentLeave() {
        init();
        StudentLeave obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return StudentLeave.findStudentLeave(id);
    }
    
    public boolean StudentLeaveDataOnDemand.modifyStudentLeave(StudentLeave obj) {
        return false;
    }
    
    public void StudentLeaveDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = StudentLeave.findStudentLeaveEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'StudentLeave' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<StudentLeave>();
        for (int i = 0; i < 10; i++) {
            StudentLeave obj = getNewTransientStudentLeave(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
