// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.school.domain;

import com.mycompany.school.domain.StudentClass;
import com.mycompany.school.domain.StudentClassDataOnDemand;
import com.mycompany.school.domain.StudentClassIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StudentClassIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StudentClassIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StudentClassIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StudentClassIntegrationTest: @Transactional;
    
    @Autowired
    StudentClassDataOnDemand StudentClassIntegrationTest.dod;
    
    @Test
    public void StudentClassIntegrationTest.testCountStudentClasses() {
        Assert.assertNotNull("Data on demand for 'StudentClass' failed to initialize correctly", dod.getRandomStudentClass());
        long count = StudentClass.countStudentClasses();
        Assert.assertTrue("Counter for 'StudentClass' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StudentClassIntegrationTest.testFindStudentClass() {
        StudentClass obj = dod.getRandomStudentClass();
        Assert.assertNotNull("Data on demand for 'StudentClass' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StudentClass' failed to provide an identifier", id);
        obj = StudentClass.findStudentClass(id);
        Assert.assertNotNull("Find method for 'StudentClass' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'StudentClass' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StudentClassIntegrationTest.testFindAllStudentClasses() {
        Assert.assertNotNull("Data on demand for 'StudentClass' failed to initialize correctly", dod.getRandomStudentClass());
        long count = StudentClass.countStudentClasses();
        Assert.assertTrue("Too expensive to perform a find all test for 'StudentClass', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<StudentClass> result = StudentClass.findAllStudentClasses();
        Assert.assertNotNull("Find all method for 'StudentClass' illegally returned null", result);
        Assert.assertTrue("Find all method for 'StudentClass' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StudentClassIntegrationTest.testFindStudentClassEntries() {
        Assert.assertNotNull("Data on demand for 'StudentClass' failed to initialize correctly", dod.getRandomStudentClass());
        long count = StudentClass.countStudentClasses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<StudentClass> result = StudentClass.findStudentClassEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'StudentClass' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'StudentClass' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StudentClassIntegrationTest.testFlush() {
        StudentClass obj = dod.getRandomStudentClass();
        Assert.assertNotNull("Data on demand for 'StudentClass' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StudentClass' failed to provide an identifier", id);
        obj = StudentClass.findStudentClass(id);
        Assert.assertNotNull("Find method for 'StudentClass' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStudentClass(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'StudentClass' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StudentClassIntegrationTest.testMergeUpdate() {
        StudentClass obj = dod.getRandomStudentClass();
        Assert.assertNotNull("Data on demand for 'StudentClass' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StudentClass' failed to provide an identifier", id);
        obj = StudentClass.findStudentClass(id);
        boolean modified =  dod.modifyStudentClass(obj);
        Integer currentVersion = obj.getVersion();
        StudentClass merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'StudentClass' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StudentClassIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'StudentClass' failed to initialize correctly", dod.getRandomStudentClass());
        StudentClass obj = dod.getNewTransientStudentClass(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'StudentClass' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'StudentClass' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'StudentClass' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StudentClassIntegrationTest.testRemove() {
        StudentClass obj = dod.getRandomStudentClass();
        Assert.assertNotNull("Data on demand for 'StudentClass' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StudentClass' failed to provide an identifier", id);
        obj = StudentClass.findStudentClass(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'StudentClass' with identifier '" + id + "'", StudentClass.findStudentClass(id));
    }
    
}
