// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.school.domain;

import com.mycompany.school.domain.EventCategory;

privileged aspect EventCategory_Roo_JavaBean {
    
    public String EventCategory.getName() {
        return this.name;
    }
    
    public void EventCategory.setName(String name) {
        this.name = name;
    }
    
}
