// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.school.domain;

import com.mycompany.school.domain.EventType;

privileged aspect EventType_Roo_JavaBean {
    
    public String EventType.getName() {
        return this.name;
    }
    
    public void EventType.setName(String name) {
        this.name = name;
    }
    
}
