// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.school.domain;

import com.mycompany.school.domain.PersonRole;

privileged aspect PersonRole_Roo_JavaBean {
    
    public String PersonRole.getRoleName() {
        return this.roleName;
    }
    
    public void PersonRole.setRoleName(String roleName) {
        this.roleName = roleName;
    }
    
}
